#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#101010"

    # Status bar
    [statusbar-bg]="#232323"
    [statusbar-fg]="#FFFFFF"

    # Session (status-left)
    [session-bg]="#FFC799"
    [session-fg]="#000000"
    [session-prefix-bg]="#FF8080"
    [session-copy-bg]="#99FFE4"
    [session-search-bg]="#FFC799"
    [session-command-bg]="#FFC799"

    # Windows
    [window-active-base]="#FFC799"
    [window-active-style]="bold"
    [window-inactive-base]="#A0A0A0"
    [window-inactive-style]="dim"
    [window-activity-style]="dim"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#99FFE4"

    # Panes
    [pane-border-active]="#FFC799"
    [pane-border-inactive]="#A0A0A0"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#C1AD9D"
    [good-base]="#99FFE4"
    [info-base]="#99FFE4"
    [warning-base]="#FFC799"
    [error-base]="#FF8080"
    [disabled-base]="#A0A0A0"

    # Messages
    [message-bg]="#232323"
    [message-fg]="#FFFFFF"

    # Popup & menu
    [popup-bg]="#232323"
    [popup-fg]="#FFFFFF"
    [popup-border]="#FFC799"
    [menu-bg]="#232323"
    [menu-fg]="#FFFFFF"
    [menu-selected-bg]="#FFC799"
    [menu-selected-fg]="#000000"
    [menu-border]="#FFC799"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#FFC799"
    [magenta]="#FFC799"
    [surface]="#232323"
)
