# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="aibox"
# Bat indexes custom TextMate themes into its cache. Rebuild only when the
# generated aibox theme is not present (normally once after apply/theme switch).
if command -v bat >/dev/null 2>&1 && ! bat --list-themes 2>/dev/null | grep -qx 'aibox'; then
    bat cache --build >/dev/null 2>&1 || true
fi
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#4E4034,bg:#101010,fg:#FFFFFF,fg+:#FFFFFF:bold,hl:#FFC799,hl+:#FFC799:bold,pointer:#FFC799,marker:#99FFE4,spinner:#FFC799,info:#A0A0A0,header:#A0A0A0,border:#A0A0A0,prompt:#FFC799:bold,query:#FFFFFF,disabled:#A0A0A0:dim,gutter:#101010,preview-bg:#101010,preview-fg:#FFFFFF,separator:#A0A0A0,label:#FFC799"
export EZA_COLORS="di=38;2;255;199;153;1:ex=38;2;153;255;228:ln=38;2;153;255;228:fi=0:or=38;2;255;128;128;1:mi=38;2;255;128;128;1:da=38;2;160;160;160;2:sn=38;2;255;199;153:sb=38;2;255;199;153:uu=38;2;160;160;160:un=38;2;160;160;160:gu=38;2;160;160;160:gn=38;2;160;160;160:ga=38;2;153;255;228;1:gm=38;2;255;199;153;1:gd=38;2;255;128;128;1:gv=38;2;255;199;153:gt=38;2;255;199;153;3:xx=38;2;160;160;160;2:da=38;2;160;160;160;2"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;255;199;153;1m'    # section headers, command names
export LESS_TERMCAP_us=$'\e[38;2;255;199;153;4m'    # options, args
export LESS_TERMCAP_so=$'\e[38;2;255;199;153;7m'  # search / status line
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;255;128;128'
