" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#FFFFFF     guibg=#101010     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#FFFFFF     guibg=#101010
hi LineNr         guifg=#5C5C5C  guibg=#101010
hi CursorLineNr   guifg=#FF7B00 guibg=#313244 gui=bold
hi CursorLine     guibg=#313244
hi CursorColumn   guibg=#313244
hi ColorColumn    guibg=#313244
hi VertSplit      guifg=#5C5C5C  guibg=#101010
hi WinSeparator   guifg=#5C5C5C  guibg=#101010
hi StatusLine     guifg=#101010     guibg=#FF7B00 gui=bold
hi StatusLineNC   guifg=#5C5C5C  guibg=#313244
hi TabLine        guifg=#5C5C5C  guibg=#313244
hi TabLineFill    guibg=#101010
hi TabLineSel     guifg=#101010     guibg=#FF7B00 gui=bold
hi SignColumn     guifg=#5C5C5C  guibg=#101010
hi FoldColumn     guifg=#5C5C5C  guibg=#101010
hi Folded         guifg=#5C5C5C  guibg=#313244
hi NonText        guifg=#5C5C5C
hi EndOfBuffer    guifg=#101010     guibg=#101010
hi SpecialKey     guifg=#5C5C5C
hi MatchParen     guifg=#FF7B00 guibg=#313244 gui=bold,underline
hi Conceal        guifg=#5C5C5C  guibg=#101010
hi Directory      guifg=#FF7B00 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guibg=#313244
hi VisualNOS      guibg=#313244
hi Search         guifg=#101010     guibg=#FF7B00 gui=bold
hi IncSearch      guifg=#101010     guibg=#FFC799 gui=bold
hi CurSearch      guifg=#101010     guibg=#FF7B00 gui=bold
hi QuickFixLine   guibg=#313244 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#FFFFFF     guibg=#313244
hi PmenuSel       guifg=#101010     guibg=#FF7B00 gui=bold
hi PmenuSbar      guibg=#313244
hi PmenuThumb     guibg=#5C5C5C
hi WildMenu       guifg=#101010     guibg=#FF7B00 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#F44747    gui=bold
hi WarningMsg     guifg=#FF7B00
hi ModeMsg        guifg=#FF7B00 gui=bold
hi MoreMsg        guifg=#99FFE4
hi Question       guifg=#FF7B00
hi Title          guifg=#FF7B00 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#5C5C5C    gui=italic
hi Constant       guifg=#FFC799
hi String         guifg=#99FFE4
hi Character      guifg=#99FFE4
hi Number         guifg=#FFC799
hi Boolean        guifg=#FFC799
hi Float          guifg=#FFC799
hi Identifier     guifg=#FFFFFF
hi Function       guifg=#FF7B00
hi Statement      guifg=#F44747
hi Conditional    guifg=#F44747
hi Repeat         guifg=#F44747
hi Label          guifg=#FF7B00
hi Operator       guifg=#FFC799
hi Keyword        guifg=#F44747
hi Exception      guifg=#F44747
hi PreProc        guifg=#FF7B00
hi Include        guifg=#F44747
hi Define         guifg=#F44747
hi Macro          guifg=#FF7B00
hi PreCondit      guifg=#FF7B00
hi Type           guifg=#FF7B00
hi StorageClass   guifg=#FF7B00
hi Structure      guifg=#FF7B00
hi Typedef        guifg=#FF7B00
hi Special        guifg=#FFC799
hi SpecialChar    guifg=#FFC799
hi Tag            guifg=#FF7B00
hi Delimiter      guifg=#FFFFFF
hi SpecialComment guifg=#5C5C5C    gui=italic
hi Debug          guifg=#FFC799
hi Underlined     guifg=#FF7B00   gui=underline
hi Ignore         guifg=#5C5C5C
hi Error          guifg=#F44747      gui=bold
hi Todo           guifg=#FF7B00   guibg=#313244 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#99FFE4    guibg=#101010
hi DiffChange     guifg=#FF7B00   guibg=#101010
hi DiffDelete     guifg=#F44747      guibg=#101010
hi DiffText       guifg=#FF7B00   guibg=#101010    gui=bold
hi diffAdded      guifg=#99FFE4
hi diffRemoved    guifg=#F44747
hi diffChanged    guifg=#FF7B00
hi diffFile       guifg=#FF7B00   gui=bold
hi diffNewFile    guifg=#99FFE4    gui=bold
hi diffOldFile    guifg=#F44747      gui=bold
hi diffLine       guifg=#5C5C5C

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#F44747
hi SpellCap       gui=undercurl guisp=#FF7B00
hi SpellLocal     gui=undercurl guisp=#FFC799
hi SpellRare      gui=undercurl guisp=#F85B2A

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#99FFE4    guibg=#101010
hi GitGutterChange       guifg=#FF7B00   guibg=#101010
hi GitGutterDelete       guifg=#F44747      guibg=#101010
hi GitGutterChangeDelete guifg=#FFC799   guibg=#101010
hi SignifySignAdd        guifg=#99FFE4    guibg=#101010
hi SignifySignChange     guifg=#FF7B00   guibg=#101010
hi SignifySignDelete     guifg=#F44747      guibg=#101010

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#FFC799  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#5C5C5C    guibg=#101010
hi NormalFloat    guifg=#FFFFFF       guibg=#313244
