" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#FFFFFF     guibg=#101010     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#FFFFFF     guibg=#101010
hi Cursor         guifg=#000000 guibg=#FFC799
hi lCursor        guifg=#000000 guibg=#FFC799
hi LineNr         guifg=#A0A0A0  guibg=#101010
hi CursorLineNr   guifg=#FFC799 guibg=#232323 gui=bold
hi CursorLine     guibg=#232323
hi CursorColumn   guibg=#232323
hi ColorColumn    guibg=#232323
hi VertSplit      guifg=#A0A0A0  guibg=#101010
hi WinSeparator   guifg=#A0A0A0  guibg=#101010
hi StatusLine     guifg=#000000 guibg=#FFC799 gui=bold
hi StatusLineNC   guifg=#A0A0A0  guibg=#232323 gui=NONE
hi TabLine        guifg=#A0A0A0  guibg=#232323 gui=NONE
hi TabLineFill    guibg=#101010
hi TabLineSel     guifg=#000000 guibg=#FFC799 gui=bold
hi SignColumn     guifg=#A0A0A0  guibg=#101010
hi FoldColumn     guifg=#A0A0A0  guibg=#101010
hi Folded         guifg=#A0A0A0  guibg=#232323
hi NonText        guifg=#A0A0A0
hi EndOfBuffer    guifg=#101010     guibg=#101010
hi SpecialKey     guifg=#A0A0A0
hi MatchParen     guifg=#FFC799 guibg=#232323 gui=bold
hi Conceal        guifg=#A0A0A0  guibg=#101010
hi Directory      guifg=#FFC799 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guifg=#FFFFFF guibg=#4E4034
hi VisualNOS      guifg=#FFFFFF guibg=#4E4034
hi Search         guifg=#101010     guibg=#FFC799 gui=bold
hi IncSearch      guifg=#101010     guibg=#FFC799 gui=bold
hi CurSearch      guifg=#000000 guibg=#FFC799 gui=bold
hi QuickFixLine   guibg=#232323 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#FFFFFF     guibg=#232323
hi PmenuSel       guifg=#000000 guibg=#FFC799 gui=bold
hi PmenuSbar      guibg=#232323
hi PmenuThumb     guibg=#A0A0A0
hi WildMenu       guifg=#000000 guibg=#FFC799 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#FF8080    gui=bold
hi WarningMsg     guifg=#FFC799 gui=bold
hi ModeMsg        guifg=#FFC799 gui=bold
hi MoreMsg        guifg=#99FFE4
hi Question       guifg=#FFC799
hi Title          guifg=#FFC799 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#A0A0A0    gui=italic
hi Constant       guifg=#FFC799
hi String         guifg=#99FFE4     gui=NONE
hi Character      guifg=#99FFE4     gui=NONE
hi Number         guifg=#FFC799    gui=NONE
hi Boolean        guifg=#FFC799    gui=NONE
hi Float          guifg=#FFC799    gui=NONE
hi Identifier     guifg=#FFFFFF
hi Function       guifg=#99FFE4      gui=NONE
hi Statement      guifg=#FFC799  gui=bold
hi Conditional    guifg=#FFC799  gui=bold
hi Repeat         guifg=#FFC799  gui=bold
hi Label          guifg=#FFC799
hi Operator       guifg=#99FFE4      gui=NONE
hi Keyword        guifg=#FFC799  gui=bold
hi Exception      guifg=#FFC799  gui=bold
hi PreProc        guifg=#FFC799
hi Include        guifg=#FFC799
hi Define         guifg=#FFC799
hi Macro          guifg=#FFC799   gui=italic
hi PreCondit      guifg=#FFC799
hi Type           guifg=#FFC799   gui=bold
hi StorageClass   guifg=#FFC799   gui=bold
hi Structure      guifg=#FFC799   gui=bold
hi Typedef        guifg=#FFC799   gui=bold
hi Special        guifg=#99FFE4
hi SpecialChar    guifg=#FFC799
hi Tag            guifg=#FFC799
hi Delimiter      guifg=#FFFFFF
hi SpecialComment guifg=#A0A0A0    gui=italic
hi Debug          guifg=#FFC799
hi Underlined     guifg=#FFC799   gui=underline
hi Ignore         guifg=#A0A0A0
hi Error          guifg=#FF8080      gui=bold
hi Todo           guifg=#FFC799   guibg=#232323 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#99FFE4    guibg=#2E453F
hi DiffChange     guifg=#FFC799   guibg=#45382E
hi DiffDelete     guifg=#FF8080      guibg=#452929
hi DiffText       guifg=#FFC799   guibg=#45382E gui=bold
hi diffAdded      guifg=#99FFE4
hi diffRemoved    guifg=#FF8080
hi diffChanged    guifg=#FFC799
hi diffFile       guifg=#FFC799   gui=bold
hi diffNewFile    guifg=#99FFE4    gui=bold
hi diffOldFile    guifg=#FF8080      gui=bold
hi diffLine       guifg=#A0A0A0

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#FF8080
hi SpellCap       gui=undercurl guisp=#FFC799
hi SpellLocal     gui=undercurl guisp=#99FFE4
hi SpellRare      gui=undercurl guisp=#FFC799

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#99FFE4    guibg=#101010
hi GitGutterChange       guifg=#FFC799   guibg=#101010
hi GitGutterDelete       guifg=#FF8080      guibg=#101010
hi GitGutterChangeDelete guifg=#FFC799   guibg=#101010
hi SignifySignAdd        guifg=#99FFE4    guibg=#101010
hi SignifySignChange     guifg=#FFC799   guibg=#101010
hi SignifySignDelete     guifg=#FF8080      guibg=#101010

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#99FFE4  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#A0A0A0    guibg=#101010
hi NormalFloat    guifg=#FFFFFF       guibg=#232323
