#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#101010"

    # Status bar
    [statusbar-bg]="#313244"
    [statusbar-fg]="#FFFFFF"

    # Session (status-left)
    [session-bg]="#FF7B00"
    [session-fg]="#101010"
    [session-prefix-bg]="#F44747"
    [session-copy-bg]="#FFC799"
    [session-search-bg]="#FF7B00"
    [session-command-bg]="#F85B2A"

    # Windows
    [window-active-base]="#FF7B00"
    [window-active-style]="bold"
    [window-inactive-base]="#5C5C5C"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#FFC799"

    # Panes
    [pane-border-active]="#FF7B00"
    [pane-border-inactive]="#5C5C5C"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#95663B"
    [good-base]="#99FFE4"
    [info-base]="#FFC799"
    [warning-base]="#FF7B00"
    [error-base]="#F44747"
    [disabled-base]="#5C5C5C"

    # Messages
    [message-bg]="#313244"
    [message-fg]="#FFFFFF"

    # Popup & menu
    [popup-bg]="#313244"
    [popup-fg]="#FFFFFF"
    [popup-border]="#FF7B00"
    [menu-bg]="#313244"
    [menu-fg]="#FFFFFF"
    [menu-selected-bg]="#FF7B00"
    [menu-selected-fg]="#101010"
    [menu-border]="#FF7B00"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#FFC799"
    [magenta]="#F85B2A"
    [surface]="#313244"
)
