apiVersion: ainfra.projectious.work/v1
kind: Deployment
metadata:
  name: example
  description: Example deployment using native OpenTofu and Ansible variables
spec:
  template:
    source: local:../template
  inputs:
    tofu:
      variableFiles:
        - terraform.tfvars
      backendConfigFiles: []
    ansible:
      variableFiles:
        - ansible-vars.yaml
  ssh:
    knownHosts: known_hosts
