" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#FFFF55     guibg=#0000AA     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#FFFF55     guibg=#0000AA
hi Cursor         guifg=#0000AA guibg=#FFFFFF
hi lCursor        guifg=#0000AA guibg=#FFFFFF
hi LineNr         guifg=#C4C4C4  guibg=#0000AA
hi CursorLineNr   guifg=#FFFFFF guibg=#000066 gui=bold
hi CursorLine     guibg=#000066
hi CursorColumn   guibg=#000066
hi ColorColumn    guibg=#000066
hi VertSplit      guifg=#C4C4C4  guibg=#0000AA
hi WinSeparator   guifg=#C4C4C4  guibg=#0000AA
hi StatusLine     guifg=#0000AA guibg=#FFFFFF gui=bold
hi StatusLineNC   guifg=#C4C4C4  guibg=#000066 gui=NONE
hi TabLine        guifg=#C4C4C4  guibg=#000066 gui=NONE
hi TabLineFill    guibg=#0000AA
hi TabLineSel     guifg=#0000AA guibg=#FFFFFF gui=bold
hi SignColumn     guifg=#C4C4C4  guibg=#0000AA
hi FoldColumn     guifg=#C4C4C4  guibg=#0000AA
hi Folded         guifg=#C4C4C4  guibg=#000066
hi NonText        guifg=#C4C4C4
hi EndOfBuffer    guifg=#0000AA     guibg=#0000AA
hi SpecialKey     guifg=#C4C4C4
hi MatchParen     guifg=#FFFFFF guibg=#000066 gui=bold
hi Conceal        guifg=#C4C4C4  guibg=#0000AA
hi Directory      guifg=#FFFFFF gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guifg=#000000 guibg=#008888
hi VisualNOS      guifg=#000000 guibg=#008888
hi Search         guifg=#0000AA     guibg=#FFFF55 gui=bold
hi IncSearch      guifg=#0000AA     guibg=#FFAA55 gui=bold
hi CurSearch      guifg=#0000AA guibg=#FFFFFF gui=bold
hi QuickFixLine   guibg=#000066 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#FFFF55     guibg=#000066
hi PmenuSel       guifg=#0000AA guibg=#FFFFFF gui=bold
hi PmenuSbar      guibg=#000066
hi PmenuThumb     guibg=#C4C4C4
hi WildMenu       guifg=#0000AA guibg=#FFFFFF gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#FF7B7B    gui=bold
hi WarningMsg     guifg=#FFFF55 gui=bold
hi ModeMsg        guifg=#FFFFFF gui=bold
hi MoreMsg        guifg=#55FF55
hi Question       guifg=#FFFFFF
hi Title          guifg=#FFFFFF gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#C4C4C4    gui=italic
hi Constant       guifg=#FFAA55
hi String         guifg=#55FF55     gui=NONE
hi Character      guifg=#55FF55     gui=NONE
hi Number         guifg=#FFAA55    gui=NONE
hi Boolean        guifg=#FFAA55    gui=NONE
hi Float          guifg=#FFAA55    gui=NONE
hi Identifier     guifg=#FFFF55
hi Function       guifg=#55FFFF      gui=bold
hi Statement      guifg=#FF8AFF  gui=bold
hi Conditional    guifg=#FF8AFF  gui=bold
hi Repeat         guifg=#FF8AFF  gui=bold
hi Label          guifg=#FFFF55
hi Operator       guifg=#55FFFF      gui=NONE
hi Keyword        guifg=#FF8AFF  gui=bold
hi Exception      guifg=#FF8AFF  gui=bold
hi PreProc        guifg=#FF8AFF
hi Include        guifg=#FF8AFF
hi Define         guifg=#FF8AFF
hi Macro          guifg=#FFFFFF   gui=italic
hi PreCondit      guifg=#FFFF55
hi Type           guifg=#FFFF55   gui=bold
hi StorageClass   guifg=#FFFF55   gui=bold
hi Structure      guifg=#FFFF55   gui=bold
hi Typedef        guifg=#FFFF55   gui=bold
hi Special        guifg=#55FFFF
hi SpecialChar    guifg=#FFAA55
hi Tag            guifg=#FFFFFF
hi Delimiter      guifg=#FFFF55
hi SpecialComment guifg=#C4C4C4    gui=italic
hi Debug          guifg=#FFAA55
hi Underlined     guifg=#FFFFFF   gui=underline
hi Ignore         guifg=#C4C4C4
hi Error          guifg=#FF7B7B      gui=bold
hi Todo           guifg=#FFFF55   guibg=#000066 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#55FF55    guibg=#003366
hi DiffChange     guifg=#FFFF55   guibg=#554400
hi DiffDelete     guifg=#FF7B7B      guibg=#550055
hi DiffText       guifg=#FFFFFF   guibg=#554400 gui=bold
hi diffAdded      guifg=#55FF55
hi diffRemoved    guifg=#FF7B7B
hi diffChanged    guifg=#FFFF55
hi diffFile       guifg=#FFFFFF   gui=bold
hi diffNewFile    guifg=#55FF55    gui=bold
hi diffOldFile    guifg=#FF7B7B      gui=bold
hi diffLine       guifg=#C4C4C4

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#FF7B7B
hi SpellCap       gui=undercurl guisp=#FFFF55
hi SpellLocal     gui=undercurl guisp=#55FFFF
hi SpellRare      gui=undercurl guisp=#FF8AFF

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#55FF55    guibg=#0000AA
hi GitGutterChange       guifg=#FFFF55   guibg=#0000AA
hi GitGutterDelete       guifg=#FF7B7B      guibg=#0000AA
hi GitGutterChangeDelete guifg=#FFAA55   guibg=#0000AA
hi SignifySignAdd        guifg=#55FF55    guibg=#0000AA
hi SignifySignChange     guifg=#FFFF55   guibg=#0000AA
hi SignifySignDelete     guifg=#FF7B7B      guibg=#0000AA

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#55FFFF  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#C4C4C4    guibg=#0000AA
hi NormalFloat    guifg=#FFFF55       guibg=#000066
