#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#2E3440"

    # Status bar
    [statusbar-bg]="#3B4252"
    [statusbar-fg]="#D8DEE9"

    # Session (status-left)
    [session-bg]="#88C0D0"
    [session-fg]="#2E3440"
    [session-prefix-bg]="#BF616A"
    [session-copy-bg]="#81A1C1"
    [session-search-bg]="#EBCB8B"
    [session-command-bg]="#A98792"

    # Windows
    [window-active-base]="#88C0D0"
    [window-active-style]="bold"
    [window-inactive-base]="#4C566A"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#81A1C1"

    # Panes
    [pane-border-active]="#88C0D0"
    [pane-border-inactive]="#4C566A"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#617B8D"
    [good-base]="#A3BE8C"
    [info-base]="#81A1C1"
    [warning-base]="#EBCB8B"
    [error-base]="#BF616A"
    [disabled-base]="#4C566A"

    # Messages
    [message-bg]="#3B4252"
    [message-fg]="#D8DEE9"

    # Popup & menu
    [popup-bg]="#3B4252"
    [popup-fg]="#D8DEE9"
    [popup-border]="#88C0D0"
    [menu-bg]="#3B4252"
    [menu-fg]="#D8DEE9"
    [menu-selected-bg]="#88C0D0"
    [menu-selected-fg]="#2E3440"
    [menu-border]="#88C0D0"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#D08770"
    [magenta]="#A98792"
    [surface]="#3B4252"
)
