" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#D8DEE9     guibg=#2E3440     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#D8DEE9     guibg=#2E3440
hi LineNr         guifg=#4C566A  guibg=#2E3440
hi CursorLineNr   guifg=#88C0D0 guibg=#3B4252 gui=bold
hi CursorLine     guibg=#3B4252
hi CursorColumn   guibg=#3B4252
hi ColorColumn    guibg=#3B4252
hi VertSplit      guifg=#4C566A  guibg=#2E3440
hi WinSeparator   guifg=#4C566A  guibg=#2E3440
hi StatusLine     guifg=#2E3440     guibg=#88C0D0 gui=bold
hi StatusLineNC   guifg=#4C566A  guibg=#3B4252
hi TabLine        guifg=#4C566A  guibg=#3B4252
hi TabLineFill    guibg=#2E3440
hi TabLineSel     guifg=#2E3440     guibg=#88C0D0 gui=bold
hi SignColumn     guifg=#4C566A  guibg=#2E3440
hi FoldColumn     guifg=#4C566A  guibg=#2E3440
hi Folded         guifg=#4C566A  guibg=#3B4252
hi NonText        guifg=#4C566A
hi EndOfBuffer    guifg=#2E3440     guibg=#2E3440
hi SpecialKey     guifg=#4C566A
hi MatchParen     guifg=#88C0D0 guibg=#3B4252 gui=bold,underline
hi Conceal        guifg=#4C566A  guibg=#2E3440
hi Directory      guifg=#88C0D0 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guibg=#3B4252
hi VisualNOS      guibg=#3B4252
hi Search         guifg=#2E3440     guibg=#EBCB8B gui=bold
hi IncSearch      guifg=#2E3440     guibg=#D08770 gui=bold
hi CurSearch      guifg=#2E3440     guibg=#88C0D0 gui=bold
hi QuickFixLine   guibg=#3B4252 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#D8DEE9     guibg=#3B4252
hi PmenuSel       guifg=#2E3440     guibg=#88C0D0 gui=bold
hi PmenuSbar      guibg=#3B4252
hi PmenuThumb     guibg=#4C566A
hi WildMenu       guifg=#2E3440     guibg=#88C0D0 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#BF616A    gui=bold
hi WarningMsg     guifg=#EBCB8B
hi ModeMsg        guifg=#88C0D0 gui=bold
hi MoreMsg        guifg=#A3BE8C
hi Question       guifg=#88C0D0
hi Title          guifg=#88C0D0 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#4C566A    gui=italic
hi Constant       guifg=#D08770
hi String         guifg=#A3BE8C
hi Character      guifg=#A3BE8C
hi Number         guifg=#D08770
hi Boolean        guifg=#D08770
hi Float          guifg=#D08770
hi Identifier     guifg=#D8DEE9
hi Function       guifg=#88C0D0
hi Statement      guifg=#BF616A
hi Conditional    guifg=#BF616A
hi Repeat         guifg=#BF616A
hi Label          guifg=#EBCB8B
hi Operator       guifg=#81A1C1
hi Keyword        guifg=#BF616A
hi Exception      guifg=#BF616A
hi PreProc        guifg=#EBCB8B
hi Include        guifg=#BF616A
hi Define         guifg=#BF616A
hi Macro          guifg=#88C0D0
hi PreCondit      guifg=#EBCB8B
hi Type           guifg=#EBCB8B
hi StorageClass   guifg=#EBCB8B
hi Structure      guifg=#EBCB8B
hi Typedef        guifg=#EBCB8B
hi Special        guifg=#81A1C1
hi SpecialChar    guifg=#D08770
hi Tag            guifg=#88C0D0
hi Delimiter      guifg=#D8DEE9
hi SpecialComment guifg=#4C566A    gui=italic
hi Debug          guifg=#D08770
hi Underlined     guifg=#88C0D0   gui=underline
hi Ignore         guifg=#4C566A
hi Error          guifg=#BF616A      gui=bold
hi Todo           guifg=#EBCB8B   guibg=#3B4252 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#A3BE8C    guibg=#2E3440
hi DiffChange     guifg=#EBCB8B   guibg=#2E3440
hi DiffDelete     guifg=#BF616A      guibg=#2E3440
hi DiffText       guifg=#88C0D0   guibg=#2E3440    gui=bold
hi diffAdded      guifg=#A3BE8C
hi diffRemoved    guifg=#BF616A
hi diffChanged    guifg=#EBCB8B
hi diffFile       guifg=#88C0D0   gui=bold
hi diffNewFile    guifg=#A3BE8C    gui=bold
hi diffOldFile    guifg=#BF616A      gui=bold
hi diffLine       guifg=#4C566A

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#BF616A
hi SpellCap       gui=undercurl guisp=#EBCB8B
hi SpellLocal     gui=undercurl guisp=#81A1C1
hi SpellRare      gui=undercurl guisp=#A98792

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#A3BE8C    guibg=#2E3440
hi GitGutterChange       guifg=#EBCB8B   guibg=#2E3440
hi GitGutterDelete       guifg=#BF616A      guibg=#2E3440
hi GitGutterChangeDelete guifg=#D08770   guibg=#2E3440
hi SignifySignAdd        guifg=#A3BE8C    guibg=#2E3440
hi SignifySignChange     guifg=#EBCB8B   guibg=#2E3440
hi SignifySignDelete     guifg=#BF616A      guibg=#2E3440

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#81A1C1  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#4C566A    guibg=#2E3440
hi NormalFloat    guifg=#D8DEE9       guibg=#3B4252
