#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#0000AA"

    # Status bar
    [statusbar-bg]="#000066"
    [statusbar-fg]="#FFFF55"

    # Session (status-left)
    [session-bg]="#FFFFFF"
    [session-fg]="#0000AA"
    [session-prefix-bg]="#FF7B7B"
    [session-copy-bg]="#55FFFF"
    [session-search-bg]="#FFFF55"
    [session-command-bg]="#FF8AFF"

    # Windows
    [window-active-base]="#FFFFFF"
    [window-active-style]="bold"
    [window-inactive-base]="#C4C4C4"
    [window-inactive-style]="dim"
    [window-activity-style]="dim"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#55FFFF"

    # Panes
    [pane-border-active]="#FFFFFF"
    [pane-border-inactive]="#C4C4C4"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#D8D8D8"
    [good-base]="#55FF55"
    [info-base]="#55FFFF"
    [warning-base]="#FFFF55"
    [error-base]="#FF7B7B"
    [disabled-base]="#C4C4C4"

    # Messages
    [message-bg]="#000066"
    [message-fg]="#FFFF55"

    # Popup & menu
    [popup-bg]="#000066"
    [popup-fg]="#FFFF55"
    [popup-border]="#FFFFFF"
    [menu-bg]="#000066"
    [menu-fg]="#FFFF55"
    [menu-selected-bg]="#FFFFFF"
    [menu-selected-fg]="#0000AA"
    [menu-border]="#FFFFFF"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#FFAA55"
    [magenta]="#FF8AFF"
    [surface]="#000066"
)
